### ISSUE TITLE
Background doesn't allow tags

### ISSUE THREAD

**Issue by schmittjoh** [Behat/Gherkin#1]
I'd like to add some tags to my background, but Gherkin throws an exception "[Behat\Gherkin\Exception\ParserException] Expected Feature token, but got Tag on line: 6".

Example below:

``` cucumber
Feature: Posts

  @database @postFixture @javascript
  Background:
    Given I am logged in as normal user
    And   I am on "/profile/"

  Scenario: I see all posts after logging in
    Then I should see a list of all current posts

  Scenario: abc etc.
```

Right now, I need to copy the tags to all scenarios, what do you think about allowing tags on background itself?

**Comment by Taluu** [comment]
It seems this is broken again, with the following :

```
@foo
Feature: My Feature

@bar
Scenario: My Scenario
when ....
```

When dumping the tags of the scenario in a "GherkinNodeTested" event via `$event->getNode()->getTags()`, I have
```
array:1 [
   0 => "bar"
]
```

And if I do a `$event->getFeature()->getTags()`, I have the following :
```
array:1 [
   0 => "foo"
]
```

While I was expecting to have 

```
array:1 [
   0 => "foo",
   1 => "bar"
]
```

in my `ScenarioNode`

Unless I missed something ?
