### ISSUE TITLE
Retain leading white space in table nodes

### ISSUE THREAD

**Issue by rudiedirkx** [Behat/Gherkin#104]
Imagine you have an `Examples` table like this:

```
Examples:
	| Quantity    | StartAmount | StartUnit | ResultAmount | ResultUnit |
	| Volume      |    1        | l         |    1         | l          |
	| Volume      |  350        | usg       | 1324.8935    | l          |
	| Volume      | 1000        | l         |  264.1722    | usg        |
	| Volume      | 1000        | l         |  219.9692    | bg         |
	| Volume      |   80        | bg        |   96.0760    | usg        |
```

Parsing and printing that table would print:

```
| Quantity | StartAmount | StartUnit | ResultAmount | ResultUnit |
| Volume   | 1           | l         | 1            | l          |
| Volume   | 350         | usg       | 1324.8935    | l          |
| Volume   | 1000        | l         | 264.1722     | usg        |
| Volume   | 1000        | l         | 219.9692     | bg         |
| Volume   | 80          | bg        | 96.0760      | usg        |
```

because leading white spaces aren't remembered after parsing. It'd be so nice to keep them, to print the exact same table as was input.

Obviously it's not very important, but it is nice. And it's possible and backward compatible, but it's not very pretty. I had to alter the `Lexer` (parse the table and **keep** left padding) and the `TableNode` (remove left padding from values, but save their sizes).

I'll create a pull request.

**Comment by stof** [comment]
sorry, but the existing behavior matches the behavior of the official gherkin parsers (which explicitly mandate that table cells are trimmed from their whitespaces), so we won't diverge from it in our own parser.

**Comment by stof** [comment]
and btw, this is *not* backward compatible, as it changes the behavior of formatted cells
