### ISSUE TITLE
Missing asterisk step keywords.

### ISSUE THREAD

**Issue by lxbzmy** [Behat/Gherkin#110]
Following gherkin specification. A step can be begin with a asterisk "*".

Ruby:
https://github.com/cucumber/gherkin/blob/master/ruby/spec/gherkin/parser_spec.rb
And Java:
https://github.com/cucumber/gherkin/blob/master/java/src/main/resources/gherkin/gherkin-languages.json
And js:
https://github.com/cucumber/gherkin/blob/master/javascript/lib/gherkin/gherkin-languages.json

And a stackoverflow why :
http://stackoverflow.com/questions/27361647/cucumber-step-definitions-must-use-given-and-then-etc

**Comment by stof** [comment]
@everzet should we include them ? Once https://github.com/Behat/Gherkin/pull/108 is merged, it will work fine

**Comment by lxbzmy** [comment]
#111  
I add a PR.

simply change 1i8n ,and use preg_quote on lexer, and also test case.

I always use "*" step,because sooo many given when then is boring。
