### ISSUE TITLE
Enable modifying TableNode data during runtime

### ISSUE THREAD

**Issue by kalinchernev** [Behat/Gherkin#114]
Hi, I have a question before making any changes that might not be complying to a design pattern or a concept.

I'm considering adding setters to https://github.com/Behat/Gherkin/blob/master/src/Behat/Gherkin/Node/TableNode.php class.

The reasoning:
I want to use a human readable date like "in 1 week" as a cell data in a table, which is later converted to a timestamp by a http://docs.behat.org/en/v2.5/guides/3.hooks.html#step-hooks
Currently, the data from the table is iterable, but not modifiable with a method.

When the date is in a regular step the transforms would be ok, but I haven't found any other ideas on how to transform/modify data in table cells.

Please tell me if this way of thinking is wrong and if I'm missing a standard pattern I have to apply?

Thanks!

**Comment by stof** [comment]
Behat supports table transformations too. This is the way to go rather than making TableNode mutable (which could break the gherkin caching)

**Comment by kalinchernev** [comment]
@stof could you please clarify on the approach with an example?

**Comment by everzet** [comment]
Gherkin AST is immutable by design. You can not change AST without changing the `*.feature` file. You can, however, use the [Behat transformations](http://behat.org/en/latest/user_guide/context/definitions.html#step-argument-transformations) for the same effect.
