### ISSUE TITLE
Add support for tags on Examples

### ISSUE THREAD

**Issue by stukalin** [Behat/Gherkin#117]
According to this https://cucumber.io/docs/reference there should be support for tags on Examples. Currently I've got an error when I add one. 

Is it planned to be added? Can I contribute?

**Comment by phil-davis** [comment]
PR #161 is the current incarnation of this feature. It is waiting for review.

**Comment by individual-it** [comment]
is that fixed by #161 ?

**Comment by phil-davis** [comment]
Yes, I will make some changes to examples tables in `owncloud/core` that will demonstrate it in "real life" and will link that here.
`Behat/Gherkin` 4.7.1 onwards supports this.

**Comment by ciaranmcnulty** [comment]
Yes, this is now working I believe

**Comment by phil-davis** [comment]
As an example, PR https://github.com/owncloud/core/pull/38358 now uses multiple example tables and works.
