### ISSUE TITLE
Tags not inherited

### ISSUE THREAD

**Issue by Taluu** [Behat/Gherkin#124]
following #1, it seems it is broken again, as in a `ScenarioNode` I don't have access to the `FeatureNode`'s tags.

With the following feature file :

```gherkin
@foo
Feature: My Feature

@bar
Scenario: My Scenario
when ....
```

When dumping the tags of the scenario in a `GherkinNodeTested` event via `$event->getNode()->getTags()` (in Behat), I have
```
array:1 [
   0 => "bar"
]
```

And if I do a `$event->getFeature()->getTags()`, I have the following :
```
array:1 [
   0 => "foo"
]
```

While I was expecting to have 

```
array:1 [
   0 => "foo",
   1 => "bar"
]
```

in my `ScenarioNode::getTags()`

Unless I missed something ?

**Comment by everzet** [comment]
Tags merging isn't reflected onto AST, they are handled dynamically by filters. It is by design in this version, for better or worse.
