### ISSUE TITLE
Support the Example keyword

### ISSUE THREAD

**Issue by ciaranmcnulty** [Behat/Gherkin#141]
as a synonym for Scenario

**Comment by ciaranmcnulty** [comment]
Actually, maybe this can be done just as a translation?

**Comment by stof** [comment]
Yeah, updating translations from Cucumber will deal with that. That's also how they implement it

**Comment by ciaranmcnulty** [comment]
@stof what's the process for doing that?

**Comment by stof** [comment]
running `bin/update_i18n` and committing the updated file. But the script might be broken, as we haven't used it since a while, and I don't remember whether the last time was before or after Cucumber reorganized their Github repos.

**Comment by ciaranmcnulty** [comment]
Seems to have done something, thanks! #142
