### ISSUE TITLE
french typo

### ISSUE THREAD

**Issue by jglhelias** [Behat/Gherkin#158]
According to the typographic rules, in French a space precedes the two-point character.

Example:
English: `text:[space]text`
French: `text[space]:[space]text`
Source: http://www.la-ponctuation.com/deux-points.html

The lexer using a regular expression (https://github.com/Behat/Gherkin/blob/master/src/Behat/Gherkin/Lexer.php#L266), it is easy to adapt the translation.

For example (being lax):
https://github.com/Behat/Gherkin/blob/master/i18n.php#L450
`    'examples' => 'Exemples\s?',`

**Comment by stof** [comment]
these translations are copied from the upstream gherkin source code, so we won't make any manual updates to it.
And the current syntax for translation does not allow regex fragments there (anything coming from this file is escaped before entering the regex).

**Comment by ciaranmcnulty** [comment]
Yes please submit this to cucumber/cucumber

Rather than a regex you could add a synonym for all of the terms that includes the space
