### ISSUE TITLE
Support language injection in cucumber doc strings

### ISSUE THREAD

**Issue by dkarlovi** [Behat/Gherkin#182]
Cucumber: https://cucumber.io/blog/open-source/announcing-cucumber-jvm-v5-0-0-rc1/#docstring

Example
```gherkin
And we interact with request "testWebService" within web service catalogue "test/v1"
"""json
{
    "method": "GET",
    "url":    "http:/localhost/ccx/api/testWebService/v1/test/contentCollection/whatsNew"
}
"""
```

At first it should just ignore it. Later it could add a validator for low hanging fruit (JSON if ext available, XML if ext available).

See:
https://youtrack.jetbrains.com/issue/IDEA-137625
https://github.com/cucumber/cucumber/pull/292#pullrequestreview-71032820

**Comment by ciaranmcnulty** [comment]
If it’s supported in cucumber we should definitely allow it here

**Comment by ciaranmcnulty** [comment]
@dkarlovi did you ever test if this works (by being ignored)?

**Comment by dkarlovi** [comment]
Yes, it works. Closing.
