### ISSUE TITLE
When creating ExampleNode outline title is never passed to contructor

### ISSUE THREAD

**Issue by latvianization** [Behat/Gherkin#197]
broken in #161 
https://github.com/Behat/Gherkin/commit/dfc47a2f796c99b8b6e6195ec277adc4ea1e36e2#diff-6e02ff2c049819aa5946c6a1577b66c4ebece9a0c2275c5aa5f7c5d209e9eba2R227

title is never passed

**Comment by ciaranmcnulty** [comment]
Hm, what is the effect of this for end users?

Is it just a 1-line change to put it back?

**Comment by latvianization** [comment]
it is one line fix, just tested and outline title is set as it was previously

`
$examples[] = new ExampleNode(
                    $exampleTable->getRowAsString($rowNum + 1),
                    array_merge($this->tags, $exampleTable->getTags()),
                    $this->getSteps(),
                    $row,
                    $exampleTable->getRowLine($rowNum + 1),
                    $this->getTitle()
                );
`

We use outline text as part of hash to save test run in custom test reporting system. If title is not provided, it is empty string which leads to identical hashes for all outline examples which then messes up our reports

**Comment by ciaranmcnulty** [comment]
Any chance you can PR? You can even do it via the Github UI :)

**Comment by latvianization** [comment]
![image](https://user-images.githubusercontent.com/58843458/106743950-b4eb2880-6627-11eb-91a5-07935a09e876.png)
