### ISSUE TITLE
Wrong hash for cucumber releases?

### ISSUE THREAD

**Issue by ciaranmcnulty** [Behat/Gherkin#223]
We get the list by running 

```
git ls-remote --tags https://github.com/cucumber/cucumber.git 
```

Which looks like:
```
580f185fb19285e42373c4cb2a88a8de66b308a3        refs/tags/cucumber-gherkin/v17.0.1
99706895df020c8d005bc6d32afe2fec691b8493        refs/tags/cucumber-gherkin/v17.0.2
```

And use that hash for the cucumber update.

However, when I look into the Github UI, that hash seems to be of the _previous_ commit?

<img width="1233" alt="Screenshot 2021-02-17 at 10 34 48" src="https://user-images.githubusercontent.com/237866/108192137-ccd4a900-710b-11eb-822d-e654ffb45937.png">

So we are potentially getting the wrong hash. The cucumber release process means this is only missing a changeling and some version numbers, but could be quite dangerous in future if unresolved

**Comment by stof** [comment]
this is due to how tags are done in the cucumber repo:
![image](https://user-images.githubusercontent.com/439401/108192864-11b10d80-7115-11eb-9984-8f1fc29b30ea.png)

they have 2 different tags on different commits

**Comment by stof** [comment]
I would say that this is probably a glitch on the cucumber side. I don't see why this would be intended.

**Comment by ciaranmcnulty** [comment]
Aha so it should be a simple fix, thank you

**Comment by stof** [comment]
well, the question is whether we even need to change something. the `cucumber-gherkin/*` tags are the one they use for the github releases.

**Comment by ciaranmcnulty** [comment]
They don't contain the changelogs and I wanted to get that into the PR

**Comment by ciaranmcnulty** [comment]
From what I can see, they release `cucumber-gherkin` which then prompts cukebot to update and sync a load of stuff, which tags `gherkin` and manages the subrepo stuff?
