### ISSUE TITLE
Migrate parser to `cucumber/common`?

### ISSUE THREAD

**Issue by ciaranmcnulty** [Behat/Gherkin#245]
I'm going to do a spike at porting the cucumber parser over to PHP within the cucumber repository. This would contain a complete AST of value objects we could use.

For BC it should be possible to write a thin translation layer to map that to the existing Gherkin objects in this repo via a Loader, but a future version of Behat could rely on its AST directly, or even at some point rely on its 'pickles'.

Pros:

* Help from Cucumber team in maintenance, as internal structure would closely mirror the Java etc implementations
* Faster support for Cucumber language features
* Would use cucumber versioning so users could pin specific translations (see #193)

Cons:

* Relies on Cucumber team caring about PHP
* Introduces a layer of complexity in mapping

Any thoughts/feedback?

**Comment by ciaranmcnulty** [comment]
Yeah it would basically be the same mapping as NdJsoNLoader does in the tests, except from cucumber objects instead of JSON

**Comment by unkind** [comment]
It requires to implement parser generator for [gasparnagy/berp](https://github.com/gasparnagy/berp) first (template file).

**Comment by ciaranmcnulty** [comment]
@unkind Just to update, I've started work on this and have a cucumber/messages implementation published on packagist

**Comment by unkind** [comment]
How it's going? Need some help?

**Comment by unkind** [comment]
Not sure about English language, but "Scenario" instead of "Example" in Russian sounds literally like "Script" for a movie or even a theatrical play. It's harder to represent to a newbies.

**Comment by ciaranmcnulty** [comment]
See #253
